import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionProvider from './SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ballet & Books',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-gray-900">
      <body className='h-full'>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
  )
}
